name = "CASA"
uuid = "c7590c19-8f20-4975-b2a9-a0df4859c40d"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
