name = "PyCASA"
uuid = "c0371cf2-69c1-404b-9565-f01b56f8974e"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.2.1"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
