name = "CASA"
uuid = "c7590c19-8f20-4975-b2a9-a0df4859c40d"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"

[targets]
test = ["Test"]
